### ISSUE TITLE
Hey This is Good. 

### ISSUE THREAD

**Issue by krishnakanthpps** [gallinazo/jmeteranalyzer#1]
Is it open source enough for me to be able to build something on this and use it myself ?

**Comment by juribes** [comment]
Hi krishnakanthpps,

The license that I like is "CC BY-NC-SA" (Attribution-NonCommercial-ShareAlike 2.0 Generic) That I think is fair (https://creativecommons.org/licenses/).

It uses canvas.js that has other license conditions (Creative Commons Attribution-NonCommercial 3.0 License) (http://canvasjs.com/license-canvasjs/) and it also uses an uploading code got from an other Githug project (https://github.com/nervgh/angular-file-upload)

If it is for you, go ahead and enjoy it. I am still working on it and I have many improvements to do.

Some of the queries are developed to only get times from HTTP 200 responses (it could be a bug but it is the initial design)

Important: the jmeter.propierties needs this configuration
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.data_type=false
jmeter.save.saveservice.label=true
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_data.on_error=false
jmeter.save.saveservice.response_message=false
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.thread_name=true
jmeter.save.saveservice.time=true
jmeter.save.saveservice.subresults=false
jmeter.save.saveservice.assertions=true
jmeter.save.saveservice.latency=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.hostname=true
jmeter.save.saveservice.thread_counts=true
jmeter.save.saveservice.sample_count=true
jmeter.save.saveservice.timestamp_format=ms
jmeter.save.saveservice.default_delimiter=,
jmeter.save.saveservice.autoflush=true
jmeter.save.saveservice.print_field_names=true

**Comment by juribes** [comment]
Solved!

The license that I like is "CC BY-NC-SA" (Attribution-NonCommercial-ShareAlike 2.0 Generic) That I think is fair (https://creativecommons.org/licenses/).

It uses canvas.js that has other license conditions (Creative Commons Attribution-NonCommercial 3.0 License) (http://canvasjs.com/license-canvasjs/) and it also uses an uploading code got from an other Githug project (https://github.com/nervgh/angular-file-upload)
